-- =============================================================================
-- SCRIPT DE CREACION DE BASE DE DATOS RELACIONAL - BD FERRETERIA
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. LIMPIEZA (orden inverso a las dependencias: hijas primero, padres despues)
-- -----------------------------------------------------------------------------
DROP TABLE IF EXISTS DET_DEVOLUCION CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS DEVOLUCION CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS MOVIMIENTOS_INVENTARIO CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS PAGOS CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS DETALLE_VENTAS CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS VENTA_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS DETALLE_COMPRA_PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS COMPRA_PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS METODOS_PAGO CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS CONDICIONES_PAGO CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS INVENTARIO CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS PRODUCTOS_PROVEEDORES CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS CATEGORIAS CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS PROVEEDORES CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS DIRECCIONES CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS CLIENTES CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS CIUDADES CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS REGIONES CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS EMPLEADOS CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS ROLES CASCADE CONSTRAINTS;

-- -----------------------------------------------------------------------------
-- 1. TABLAS DEL MODULO GEOGRAFICO Y USUARIOS
-- -----------------------------------------------------------------------------

CREATE TABLE ROLES (
    ID_ROL          NUMBER NOT NULL,
    NOMBRE          VARCHAR2(50) NOT NULL,
    DESCRIPCION     VARCHAR2(200),
    CONSTRAINT PK_ROLES PRIMARY KEY (ID_ROL)
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO     NUMBER NOT NULL,
    RUT             VARCHAR2(12) NOT NULL UNIQUE,
    NOMBRES         VARCHAR2(100) NOT NULL,
    APELLIDOS       VARCHAR2(100) NOT NULL,
    FECHA_INGRESO   DATE DEFAULT SYSDATE NOT NULL,
    ACTIVO          CHAR(1) DEFAULT 'S' NOT NULL,
    ID_ROL          NUMBER NOT NULL,
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT FK_EMP_ROL FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL),
    CONSTRAINT CHK_EMP_ACTIVO CHECK (ACTIVO IN ('S', 'N'))
);

CREATE TABLE REGIONES (
    ID_REGION       NUMBER NOT NULL,
    NOMBRE          VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_REGIONES PRIMARY KEY (ID_REGION)
);

CREATE TABLE CIUDADES (
    ID_CIUDAD       NUMBER NOT NULL,
    NOMBRE          VARCHAR2(100) NOT NULL,
    REGION_ID       NUMBER NOT NULL,
    CONSTRAINT PK_CIUDADES PRIMARY KEY (ID_CIUDAD),
    CONSTRAINT FK_CIU_REGION FOREIGN KEY (REGION_ID) REFERENCES REGIONES(ID_REGION)
);

CREATE TABLE CLIENTES (
    ID_CLIENTE      NUMBER NOT NULL,
    RUT             VARCHAR2(12) NOT NULL UNIQUE,
    NOMBRES         VARCHAR2(100) NOT NULL,
    APELLIDOS       VARCHAR2(100) NOT NULL,
    CORREO          VARCHAR2(150),
    TELEFONO        VARCHAR2(20),
    DIRECCION       VARCHAR2(200),
    FECHA_REGISTRO  DATE DEFAULT SYSDATE NOT NULL,
    ACTIVO          CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT CHK_CLI_ACTIVO CHECK (ACTIVO IN ('S', 'N'))
);

CREATE TABLE DIRECCIONES (
    ID_DIRECCION    NUMBER NOT NULL,
    CALLE           VARCHAR2(150) NOT NULL,
    CODIGO_POSTAL   VARCHAR2(10),
    TIPO            VARCHAR2(30) DEFAULT 'ENTREGA',
    CIUDAD_ID       NUMBER NOT NULL,
    CLIENTE_ID      NUMBER NOT NULL,
    CONSTRAINT PK_DIRECCIONES PRIMARY KEY (ID_DIRECCION),
    CONSTRAINT FK_DIR_CIUDAD FOREIGN KEY (CIUDAD_ID) REFERENCES CIUDADES(ID_CIUDAD),
    CONSTRAINT FK_DIR_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID_CLIENTE)
);

-- -----------------------------------------------------------------------------
-- 2. TABLAS DEL MODULO DE PRODUCTOS E INVENTARIO
-- -----------------------------------------------------------------------------

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR    NUMBER NOT NULL,
    RUT             VARCHAR2(12) NOT NULL UNIQUE,
    RAZON_SOCIAL    VARCHAR2(150) NOT NULL,
    CONTACTO_NOMBRE VARCHAR2(100),
    CORREO          VARCHAR2(150),
    TELEFONO        VARCHAR2(20),
    ACTIVO          CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID_PROVEEDOR),
    CONSTRAINT CHK_PROV_ACTIVO CHECK (ACTIVO IN ('S', 'N'))
);

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA    NUMBER NOT NULL,
    NOMBRE          VARCHAR2(100) NOT NULL,
    DESCRIPCION     VARCHAR2(250),
    CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO     NUMBER NOT NULL,
    CODIGO          VARCHAR2(50) NOT NULL UNIQUE,
    NOMBRE          VARCHAR2(150) NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    PRECIO_VENTA    NUMBER(12, 2) NOT NULL,
    ID_CATEGORIA    NUMBER NOT NULL,
    ACTIVO          CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_PROD_CAT FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
    CONSTRAINT CHK_PROD_ACTIVO CHECK (ACTIVO IN ('S', 'N'))
);

CREATE TABLE PRODUCTOS_PROVEEDORES (
    ID_PRODUCTO_PROVEEDOR NUMBER NOT NULL,
    ID_PRODUCTO           NUMBER NOT NULL,
    ID_PROVEEDOR          NUMBER NOT NULL,
    COSTO_COMPRA          NUMBER(12, 2) NOT NULL,
    CONSTRAINT PK_PROD_PROV PRIMARY KEY (ID_PRODUCTO_PROVEEDOR),
    CONSTRAINT FK_PP_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
    CONSTRAINT FK_PP_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

CREATE TABLE INVENTARIO (
    ID_INVENTARIO   NUMBER NOT NULL,
    ID_PRODUCTO     NUMBER NOT NULL UNIQUE,
    CANTIDAD        NUMBER DEFAULT 0 NOT NULL,
    CANTIDAD_MINIMA NUMBER DEFAULT 5 NOT NULL,
    CONSTRAINT PK_INVENTARIO PRIMARY KEY (ID_INVENTARIO),
    CONSTRAINT FK_INV_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE CONDICIONES_PAGO (
    ID_CONDICION_PAGO NUMBER NOT NULL,
    NOMBRE            VARCHAR2(50) NOT NULL,
    DIAS_PLAZO        NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CONDICIONES_PAGO PRIMARY KEY (ID_CONDICION_PAGO)
);

CREATE TABLE METODOS_PAGO (
    ID_METODO_PAGO  NUMBER NOT NULL,
    NOMBRE          VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_METODOS_PAGO PRIMARY KEY (ID_METODO_PAGO)
);

-- -----------------------------------------------------------------------------
-- 3. TABLAS DEL MODULO DE COMPRAS (COMPRA DE STOCK)
-- -----------------------------------------------------------------------------

CREATE TABLE COMPRA_PROVEEDOR (
    ID_COMPRA_STOCK   NUMBER NOT NULL,
    ID_PROVEEDOR      NUMBER NOT NULL,
    ID_EMPLEADO       NUMBER NOT NULL,
    ID_CONDICION_PAGO NUMBER NOT NULL,
    FECHA_COMPRA      DATE DEFAULT SYSDATE NOT NULL,
    ESTADO            VARCHAR2(20) DEFAULT 'COMPLETADO' NOT NULL,
    CONSTRAINT PK_COMPRA_STOCK PRIMARY KEY (ID_COMPRA_STOCK),
    CONSTRAINT FK_CS_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR),
    CONSTRAINT FK_CS_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_CS_CONDICION FOREIGN KEY (ID_CONDICION_PAGO) REFERENCES CONDICIONES_PAGO(ID_CONDICION_PAGO)
);

CREATE TABLE DETALLE_COMPRA_PROVEEDOR (
    ID_DETALLE_COMPRA NUMBER NOT NULL,
    ID_COMPRA_STOCK   NUMBER NOT NULL,
    ID_PRODUCTO       NUMBER NOT NULL,
    CANTIDAD          NUMBER NOT NULL,
    COSTO_UNITARIO    NUMBER(12, 2) NOT NULL,
    CONSTRAINT PK_DET_COM_STOCK PRIMARY KEY (ID_DETALLE_COMPRA),
    CONSTRAINT FK_DCS_COMPRA FOREIGN KEY (ID_COMPRA_STOCK) REFERENCES COMPRA_PROVEEDOR(ID_COMPRA_STOCK),
    CONSTRAINT FK_DCS_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

-- -----------------------------------------------------------------------------
-- 4. TABLAS DEL MODULO DE VENTAS Y PAGOS
-- -----------------------------------------------------------------------------

CREATE TABLE VENTA_CLIENTE (
    ID_COMPRA_CLIENTE NUMBER NOT NULL,
    ID_CLIENTE        NUMBER NOT NULL,
    ID_EMPLEADO       NUMBER NOT NULL,
    ID_CONDICION_PAGO NUMBER NOT NULL,
    FECHA_VENTA       DATE DEFAULT SYSDATE NOT NULL,
    ESTADO            VARCHAR2(20) DEFAULT 'EMITIDA' NOT NULL,
    CONSTRAINT PK_VENTA_CLIENTE PRIMARY KEY (ID_COMPRA_CLIENTE),
    CONSTRAINT FK_VC_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_VC_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_VC_CONDICION FOREIGN KEY (ID_CONDICION_PAGO) REFERENCES CONDICIONES_PAGO(ID_CONDICION_PAGO)
);

CREATE TABLE DETALLE_VENTAS (
    ID_DETALLE_VENTA  NUMBER NOT NULL,
    ID_COMPRA_CLIENTE NUMBER NOT NULL,
    ID_PRODUCTO       NUMBER NOT NULL,
    CANTIDAD          NUMBER NOT NULL,
    PRECIO_UNITARIO   NUMBER(12, 2) NOT NULL,
    DESCUENTO         NUMBER(12, 2) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_DETALLE_VENTAS PRIMARY KEY (ID_DETALLE_VENTA),
    CONSTRAINT FK_DV_VENTA FOREIGN KEY (ID_COMPRA_CLIENTE) REFERENCES VENTA_CLIENTE(ID_COMPRA_CLIENTE),
    CONSTRAINT FK_DV_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE PAGOS (
    ID_PAGO           NUMBER NOT NULL,
    ID_COMPRA_CLIENTE NUMBER NOT NULL,
    ID_METODO_PAGO    NUMBER NOT NULL,
    MONTO             NUMBER(12, 2) NOT NULL,
    FECHA_PAGO        DATE DEFAULT SYSDATE NOT NULL,
    ESTADO            VARCHAR2(20) DEFAULT 'APROBADO' NOT NULL,
    CONSTRAINT PK_PAGOS PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_PAGO_VENTA FOREIGN KEY (ID_COMPRA_CLIENTE) REFERENCES VENTA_CLIENTE(ID_COMPRA_CLIENTE),
    CONSTRAINT FK_PAGO_METODO FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODOS_PAGO(ID_METODO_PAGO)
);

-- -----------------------------------------------------------------------------
-- 5. TABLA DE AUDITORIA Y MOVIMIENTOS DE INVENTARIO
-- -----------------------------------------------------------------------------

CREATE TABLE MOVIMIENTOS_INVENTARIO (
    ID_MOVIMIENTO    NUMBER NOT NULL,
    ID_PRODUCTO      NUMBER NOT NULL,
    ID_EMPLEADO      NUMBER NOT NULL,
    TIPO_MOVIMIENTO  VARCHAR2(20) NOT NULL, -- 'ENTRADA', 'SALIDA', 'AJUSTE'
    CANTIDAD         NUMBER NOT NULL,
    FECHA_MOVIMIENTO DATE DEFAULT SYSDATE NOT NULL,
    REFERENCIA       VARCHAR2(100),
    CONSTRAINT PK_MOVIMIENTOS PRIMARY KEY (ID_MOVIMIENTO),
    CONSTRAINT FK_MOV_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
    CONSTRAINT FK_MOV_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);

-- -----------------------------------------------------------------------------
-- 6. TABLAS DEL MODULO DE DEVOLUCIONES
-- -----------------------------------------------------------------------------

CREATE TABLE DEVOLUCION (
    ID_DEVOLUCION      NUMBER NOT NULL,
    ID_COMPRA_CLIENTE  NUMBER NOT NULL,
    ID_EMPLEADO        NUMBER NOT NULL,
    MOTIVO             VARCHAR2(150) NOT NULL,
    FECHA_DEVOLUCION   DATE DEFAULT SYSDATE NOT NULL,
    ESTADO             VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    OBSERVACION        VARCHAR2(300),
    CONSTRAINT PK_DEVOLUCION PRIMARY KEY (ID_DEVOLUCION),
    CONSTRAINT FK_DEV_VENTA FOREIGN KEY (ID_COMPRA_CLIENTE) REFERENCES VENTA_CLIENTE(ID_COMPRA_CLIENTE),
    CONSTRAINT FK_DEV_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT CHK_DEV_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'APROBADA', 'RECHAZADA', 'COMPLETADA'))
);

CREATE TABLE DET_DEVOLUCION (
    ID_DETALLE_DEVOLUCION NUMBER NOT NULL,
    ID_DEVOLUCION         NUMBER NOT NULL,
    ID_DETALLE_VENTA      NUMBER NOT NULL,
    CANTIDAD              NUMBER NOT NULL,
    MONTO_REEMBOLSO       NUMBER(12, 2) NOT NULL,
    CONSTRAINT PK_DET_DEVOLUCION PRIMARY KEY (ID_DETALLE_DEVOLUCION),
    CONSTRAINT FK_DD_DEVOLUCION FOREIGN KEY (ID_DEVOLUCION) REFERENCES DEVOLUCION(ID_DEVOLUCION),
    CONSTRAINT FK_DD_DETALLE_VENTA FOREIGN KEY (ID_DETALLE_VENTA) REFERENCES DETALLE_VENTAS(ID_DETALLE_VENTA),
    CONSTRAINT CHK_DD_CANTIDAD CHECK (CANTIDAD > 0)
);

-- -----------------------------------------------------------------------------
-- 7. VERIFICACION
-- -----------------------------------------------------------------------------
SELECT table_name FROM user_tables ORDER BY table_name;
