-- ============================================================
-- EV1 BDY1103 - Ferreteria ViSol
-- ============================================================

-- ---------- Limpieza de objetos PL/SQL previos (si existen) ----------
DROP TRIGGER IF EXISTS trg_auditoria_detalle;
DROP TRIGGER IF EXISTS trg_auditoria_pedido;
DROP TRIGGER IF EXISTS trg_alerta_stock_critico;
DROP TRIGGER IF EXISTS trg_valida_stock_negativo;
DROP PACKAGE IF EXISTS pkg_gestion_pedidos;
DROP PROCEDURE IF EXISTS sp_registrar_pedido;
DROP FUNCTION IF EXISTS fn_calcular_total_pedido;
DROP VIEW IF EXISTS vw_pedidos_totales;
DROP TYPE IF EXISTS t_id_array;
DROP TYPE IF EXISTS t_qty_array;

-- ---------- Limpieza de tablas (si existen) ----------
DROP TABLE IF EXISTS usuarios CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS reportes CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS pagos CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS detalle_pedidos CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS pedidos CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS inventarios CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS productos CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS marcas CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS categorias CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS direcciones CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS clientes CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS ciudades CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS regiones CASCADE CONSTRAINTS;

-- ============================================================
-- 1. REGIONES
CREATE TABLE regiones (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE
);

-- ============================================================
-- 2. CIUDADES
CREATE TABLE ciudades (
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR2(100) NOT NULL,
    region_id NUMBER NOT NULL REFERENCES regiones(id),
    CONSTRAINT uq_ciudad_region UNIQUE (nombre, region_id)  -- agregado: evita duplicar la misma ciudad en la misma region
);

-- ============================================================
-- 3. CLIENTES
CREATE TABLE clientes (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR2(200) NOT NULL,
    email    VARCHAR2(150) NOT NULL UNIQUE,
    telefono VARCHAR2(20) NOT NULL,
    activo   CHAR(1) DEFAULT 'S' NOT NULL  -- soft-delete: aporte de Seba
);

-- ============================================================
-- 4. DIRECCIONES
CREATE TABLE direcciones (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle         VARCHAR2(200) NOT NULL,
    ciudad_id     NUMBER NOT NULL REFERENCES ciudades(id),
    codigo_postal VARCHAR2(20),
    tipo          VARCHAR2(30) NOT NULL,
    cliente_id    NUMBER NOT NULL REFERENCES clientes(id) ON DELETE CASCADE
);

-- ============================================================
-- 5. CATEGORIAS
CREATE TABLE categorias (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE
);

-- ============================================================
-- 6. MARCAS
CREATE TABLE marcas (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE
);

-- ============================================================
-- 7. PRODUCTOS
CREATE TABLE productos (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(200) NOT NULL,
    descripcion  VARCHAR2(500),
    precio       NUMBER(12,2) NOT NULL,
    sku          VARCHAR2(50) NOT NULL UNIQUE,
    categoria_id NUMBER REFERENCES categorias(id) ON DELETE SET NULL,
    marca_id     NUMBER REFERENCES marcas(id) ON DELETE SET NULL,
    activo       CHAR(1) DEFAULT 'S' NOT NULL  -- soft-delete: aporte de Seba
);

-- ============================================================
-- 8. INVENTARIOS
CREATE TABLE inventarios (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id     NUMBER NOT NULL UNIQUE REFERENCES productos(id) ON DELETE CASCADE,
    cantidad        NUMBER NOT NULL,
    cantidad_minima NUMBER NOT NULL,
    ubicacion       VARCHAR2(100) NOT NULL
);

-- ============================================================
-- 9. PEDIDOS
CREATE TABLE pedidos (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL REFERENCES clientes(id),
    estado     VARCHAR2(30) NOT NULL,
    fecha      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL  -- default: aporte de Seba
);

-- ============================================================
-- 10. DETALLE_PEDIDOS
CREATE TABLE detalle_pedidos (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       NUMBER NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
    producto_id     NUMBER NOT NULL REFERENCES productos(id),
    cantidad        NUMBER NOT NULL,
    precio_unitario NUMBER(12,2) NOT NULL,
    UNIQUE (pedido_id, producto_id)  -- agregado: evita duplicar el mismo producto como 2 lineas de un pedido
);

-- ============================================================
-- 11. PAGOS
CREATE TABLE pagos (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id   NUMBER NOT NULL REFERENCES pedidos(id),
    monto       NUMBER(12,2) NOT NULL,
    metodo_pago VARCHAR2(50) NOT NULL,
    estado      VARCHAR2(30) NOT NULL,
    fecha       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ============================================================
-- 12. REPORTES
CREATE TABLE reportes (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id        NUMBER REFERENCES pedidos(id) ON DELETE SET NULL,
    tipo             VARCHAR2(100) NOT NULL,
    descripcion      VARCHAR2(500) NOT NULL,
    fecha_generacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    estado           VARCHAR2(30) NOT NULL
);

-- ============================================================
-- 13. USUARIOS
CREATE TABLE usuarios (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(200) NOT NULL,
    rol      VARCHAR2(30) NOT NULL,
    activo   CHAR(1) DEFAULT 'S' NOT NULL  -- soft-delete: aporte de Seba
);

-- ============================================================
-- Vista: total por pedido (propia, no duplica el dato)

CREATE OR REPLACE VIEW vw_pedidos_totales AS
SELECT p.id AS pedido_id, p.cliente_id, p.estado, p.fecha,
       SUM(dp.cantidad * dp.precio_unitario) AS total
FROM pedidos p
JOIN detalle_pedidos dp ON dp.pedido_id = p.id
GROUP BY p.id, p.cliente_id, p.estado, p.fecha;

-- ============================================================
-- Verificar tablas creadas

SELECT table_name
FROM user_tables
ORDER BY table_name;
