-- ============================================================
-- EV1 BDY1103 - Ferreteria ViSol
-- Esquema maestro v2: pedidos separado en cabecera/detalle,
-- ciudad/region normalizadas, politica ON DELETE explicita
-- ============================================================

-- ---------- Limpieza (por si existe una version anterior) ----------
DROP TRIGGER IF EXISTS trg_auditoria_pedido;
DROP TRIGGER IF EXISTS trg_alerta_stock_critico;
DROP TRIGGER IF EXISTS trg_valida_stock_negativo;
DROP PACKAGE IF EXISTS pkg_gestion_pedidos;
DROP PROCEDURE IF EXISTS sp_registrar_pedido;
DROP FUNCTION IF EXISTS fn_calcular_total_pedido;
DROP VIEW IF EXISTS vw_pedidos_totales;

DROP TABLE IF EXISTS reportes CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS pagos CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS detalle_pedidos CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS pedidos CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS inventarios CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS productos CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS marcas CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS categorias CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS direcciones CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS ciudades CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS regiones CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS clientes CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS usuarios CASCADE CONSTRAINTS;

-- ---------- Tablas base ----------
CREATE TABLE clientes (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR2(200) NOT NULL,
    email    VARCHAR2(150) NOT NULL UNIQUE,
    telefono VARCHAR2(20) NOT NULL
);

CREATE TABLE regiones (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE ciudades (
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR2(100) NOT NULL,
    region_id NUMBER NOT NULL REFERENCES regiones(id),
    CONSTRAINT uq_ciudad_region UNIQUE (nombre, region_id)
);

CREATE TABLE direcciones (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle         VARCHAR2(200) NOT NULL,
    codigo_postal VARCHAR2(20),
    tipo          VARCHAR2(30),
    ciudad_id     NUMBER NOT NULL REFERENCES ciudades(id),
    cliente_id    NUMBER NOT NULL REFERENCES clientes(id) ON DELETE CASCADE
);

CREATE TABLE categorias (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE marcas (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE productos (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(200) NOT NULL,
    descripcion  VARCHAR2(500) NOT NULL,
    precio       NUMBER(10,2) NOT NULL,
    sku          VARCHAR2(50) NOT NULL UNIQUE,
    categoria_id NUMBER REFERENCES categorias(id) ON DELETE SET NULL,
    marca_id     NUMBER REFERENCES marcas(id) ON DELETE SET NULL
);

CREATE TABLE inventarios (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id     NUMBER NOT NULL UNIQUE REFERENCES productos(id) ON DELETE CASCADE,
    cantidad        NUMBER NOT NULL,
    cantidad_minima NUMBER NOT NULL,
    ubicacion       VARCHAR2(100) NOT NULL
);

-- Cabecera del pedido: ya NO guarda producto/cantidad/precio ni total
CREATE TABLE pedidos (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL REFERENCES clientes(id),  -- sin cascada: no se borra cliente con historial
    estado     VARCHAR2(50) NOT NULL,
    fecha      TIMESTAMP NOT NULL
);

-- Detalle: una fila por cada producto dentro de un pedido
CREATE TABLE detalle_pedidos (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       NUMBER NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
    producto_id     NUMBER NOT NULL REFERENCES productos(id),  -- sin cascada: no se borra producto con historial
    cantidad        NUMBER NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL
);

CREATE TABLE pagos (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id   NUMBER NOT NULL REFERENCES pedidos(id),  -- sin cascada: no se borra pedido con pagos
    monto       NUMBER(10,2) NOT NULL,
    metodo_pago VARCHAR2(50) NOT NULL,
    estado      VARCHAR2(50) NOT NULL,
    fecha       TIMESTAMP NOT NULL
);

CREATE TABLE reportes (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id        NUMBER REFERENCES pedidos(id) ON DELETE SET NULL,
    tipo             VARCHAR2(100) NOT NULL,
    descripcion      VARCHAR2(500) NOT NULL,
    fecha_generacion TIMESTAMP NOT NULL,
    estado           VARCHAR2(50) NOT NULL
);

CREATE TABLE usuarios (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    rol      VARCHAR2(50) NOT NULL
);

-- ---------- Vista: total por pedido, SIN guardar el dato duplicado ----------
CREATE OR REPLACE VIEW vw_pedidos_totales AS
SELECT p.id AS pedido_id, p.cliente_id, p.estado, p.fecha,
       SUM(dp.cantidad * dp.precio_unitario) AS total
FROM pedidos p
JOIN detalle_pedidos dp ON dp.pedido_id = p.id
GROUP BY p.id, p.cliente_id, p.estado, p.fecha;
