-- ============================================================================
-- BD_FERRETERIA 
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1-2. ROLES Y EMPLEADOS
-- ----------------------------------------------------------------------------
INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION) VALUES (1, 'Administrador', 'Acceso total al sistema');
INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION) VALUES (2, 'Vendedor', 'Cotizaciones y ventas');
INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION) VALUES (3, 'Bodeguero', 'Inventario y recepciones');
INSERT INTO ROLES (ID_ROL, NOMBRE, DESCRIPCION) VALUES (4, 'Cajero', 'Pagos y caja');

INSERT INTO EMPLEADOS (ID_EMPLEADO, RUT, NOMBRES, APELLIDOS, FECHA_INGRESO, ACTIVO, ID_ROL)
VALUES (1, '15111222-3', 'Carlos', 'Muñoz', TO_DATE('2022-01-10','YYYY-MM-DD'), 'S', 1);
INSERT INTO EMPLEADOS (ID_EMPLEADO, RUT, NOMBRES, APELLIDOS, FECHA_INGRESO, ACTIVO, ID_ROL)
VALUES (2, '16222333-4', 'Ana', 'Rojas', TO_DATE('2022-06-15','YYYY-MM-DD'), 'S', 2);
INSERT INTO EMPLEADOS (ID_EMPLEADO, RUT, NOMBRES, APELLIDOS, FECHA_INGRESO, ACTIVO, ID_ROL)
VALUES (3, '17333444-5', 'Luis', 'Fernández', TO_DATE('2023-02-20','YYYY-MM-DD'), 'S', 3);
INSERT INTO EMPLEADOS (ID_EMPLEADO, RUT, NOMBRES, APELLIDOS, FECHA_INGRESO, ACTIVO, ID_ROL)
VALUES (4, '18444555-6', 'Paula', 'Díaz', TO_DATE('2023-05-05','YYYY-MM-DD'), 'S', 4);

-- ----------------------------------------------------------------------------
-- REGIONES Y CIUDADES
-- ----------------------------------------------------------------------------
INSERT INTO REGIONES (ID_REGION, NOMBRE) VALUES (1, 'Metropolitana');
INSERT INTO REGIONES (ID_REGION, NOMBRE) VALUES (2, 'Valparaiso');
INSERT INTO REGIONES (ID_REGION, NOMBRE) VALUES (3, 'Biobio');

INSERT INTO CIUDADES (ID_CIUDAD, NOMBRE, REGION_ID) VALUES (1, 'Santiago', 1);
INSERT INTO CIUDADES (ID_CIUDAD, NOMBRE, REGION_ID) VALUES (2, 'Valparaiso', 2);
INSERT INTO CIUDADES (ID_CIUDAD, NOMBRE, REGION_ID) VALUES (3, 'Concepcion', 3);

-- ----------------------------------------------------------------------------
-- 3-4. CLIENTES Y PROVEEDORES
-- ----------------------------------------------------------------------------
INSERT INTO CLIENTES (ID_CLIENTE, RUT, NOMBRES, APELLIDOS, CORREO, TELEFONO, DIRECCION, FECHA_REGISTRO, ACTIVO)
VALUES (1, '12345678-9', 'Juan', 'Pérez', 'juan.perez@mail.com', '+56912345678', NULL, TO_DATE('2024-01-15','YYYY-MM-DD'), 'S');
INSERT INTO CLIENTES (ID_CLIENTE, RUT, NOMBRES, APELLIDOS, CORREO, TELEFONO, DIRECCION, FECHA_REGISTRO, ACTIVO)
VALUES (2, '98765432-1', 'María', 'González', 'maria.gonzalez@mail.com', '+56987654321', NULL, TO_DATE('2024-03-10','YYYY-MM-DD'), 'S');
INSERT INTO CLIENTES (ID_CLIENTE, RUT, NOMBRES, APELLIDOS, CORREO, TELEFONO, DIRECCION, FECHA_REGISTRO, ACTIVO)
VALUES (3, '11222333-4', 'Pedro', 'Soto', 'pedro.soto@mail.com', '+56911223344', NULL, TO_DATE('2025-02-01','YYYY-MM-DD'), 'S');

INSERT INTO DIRECCIONES (ID_DIRECCION, CALLE, CODIGO_POSTAL, TIPO, CIUDAD_ID, CLIENTE_ID)
VALUES (1, 'Av. Libertador 1234', '7500000', 'ENTREGA', 1, 1);
INSERT INTO DIRECCIONES (ID_DIRECCION, CALLE, CODIGO_POSTAL, TIPO, CIUDAD_ID, CLIENTE_ID)
VALUES (2, 'Los Alerces 567', '2340000', 'ENTREGA', 2, 2);
INSERT INTO DIRECCIONES (ID_DIRECCION, CALLE, CODIGO_POSTAL, TIPO, CIUDAD_ID, CLIENTE_ID)
VALUES (3, 'Camino Real 89', '4030000', 'ENTREGA', 3, 3);

INSERT INTO PROVEEDORES (ID_PROVEEDOR, RUT, RAZON_SOCIAL, CONTACTO_NOMBRE, CORREO, TELEFONO, ACTIVO)
VALUES (1, '76111222-3', 'Distribuidora Ferretera Ltda.', 'Rodrigo Silva', 'ventas@distfer.cl', '224567890', 'S');
INSERT INTO PROVEEDORES (ID_PROVEEDOR, RUT, RAZON_SOCIAL, CONTACTO_NOMBRE, CORREO, TELEFONO, ACTIVO)
VALUES (2, '76222333-4', 'Comercial Bosch Chile SA', 'Francisca Lagos', 'contacto@boschchile.cl', '225678901', 'S');
INSERT INTO PROVEEDORES (ID_PROVEEDOR, RUT, RAZON_SOCIAL, CONTACTO_NOMBRE, CORREO, TELEFONO, ACTIVO)
VALUES (3, '76333444-5', 'Pinturas del Sur SpA', 'Jorge Vidal', 'contacto@pinturasur.cl', '+56922334455', 'S');

-- ----------------------------------------------------------------------------
-- 5-7. CATEGORIAS, PRODUCTOS, PRODUCTOS_PROVEEDORES, INVENTARIO
-- ----------------------------------------------------------------------------
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (1, 'Herramientas Manuales', 'Martillos, destornilladores, llaves');
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (2, 'Materiales de Construcción', 'Cemento, fierro, áridos');
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (3, 'Pinturas y Barnices', 'Pinturas interiores, exteriores y barnices');
INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (4, 'Ferretería General', 'Tornillos, clavos, alambres');

INSERT INTO PRODUCTOS (ID_PRODUCTO, CODIGO, NOMBRE, DESCRIPCION, PRECIO_VENTA, ID_CATEGORIA, ACTIVO)
VALUES (1, 'HM-001', 'Martillo Carpintero 16oz', 'Martillo con mango de fibra de vidrio', 8990, 1, 'S');
INSERT INTO PRODUCTOS (ID_PRODUCTO, CODIGO, NOMBRE, DESCRIPCION, PRECIO_VENTA, ID_CATEGORIA, ACTIVO)
VALUES (2, 'HM-002', 'Taladro Percutor Bosch', 'Taladro percutor 650W', 45990, 1, 'S');
INSERT INTO PRODUCTOS (ID_PRODUCTO, CODIGO, NOMBRE, DESCRIPCION, PRECIO_VENTA, ID_CATEGORIA, ACTIVO)
VALUES (3, 'MC-001', 'Cemento Portland 25kg', 'Saco de cemento gris', 6490, 2, 'S');
INSERT INTO PRODUCTOS (ID_PRODUCTO, CODIGO, NOMBRE, DESCRIPCION, PRECIO_VENTA, ID_CATEGORIA, ACTIVO)
VALUES (4, 'MC-002', 'Fierro Estriado 8mm', 'Barra de refuerzo de 6 metros', 4290, 2, 'S');
INSERT INTO PRODUCTOS (ID_PRODUCTO, CODIGO, NOMBRE, DESCRIPCION, PRECIO_VENTA, ID_CATEGORIA, ACTIVO)
VALUES (5, 'PB-001', 'Pintura Látex Blanco 1GL', 'Pintura interior/exterior', 15990, 3, 'S');
INSERT INTO PRODUCTOS (ID_PRODUCTO, CODIGO, NOMBRE, DESCRIPCION, PRECIO_VENTA, ID_CATEGORIA, ACTIVO)
VALUES (6, 'PB-002', 'Barniz Marino Transparente', 'Barniz para exteriores', 12990, 3, 'S');
INSERT INTO PRODUCTOS (ID_PRODUCTO, CODIGO, NOMBRE, DESCRIPCION, PRECIO_VENTA, ID_CATEGORIA, ACTIVO)
VALUES (7, 'FG-001', 'Tornillos Autorroscantes 1"', 'Caja de 100 unidades', 3990, 4, 'S');
INSERT INTO PRODUCTOS (ID_PRODUCTO, CODIGO, NOMBRE, DESCRIPCION, PRECIO_VENTA, ID_CATEGORIA, ACTIVO)
VALUES (8, 'FG-002', 'Alambre Galvanizado N°16', 'Rollo de 1 kilogramo', 2990, 4, 'S');

-- PRODUCTOS_PROVEEDORES: el Taladro (2) y el Cemento (3) tienen 2 proveedores
-- con costo distinto, para poder comparar costos entre proveedores.
INSERT INTO PRODUCTOS_PROVEEDORES (ID_PRODUCTO_PROVEEDOR, ID_PRODUCTO, ID_PROVEEDOR, COSTO_COMPRA) VALUES (1, 1, 1, 5500);
INSERT INTO PRODUCTOS_PROVEEDORES (ID_PRODUCTO_PROVEEDOR, ID_PRODUCTO, ID_PROVEEDOR, COSTO_COMPRA) VALUES (2, 2, 2, 32000);
INSERT INTO PRODUCTOS_PROVEEDORES (ID_PRODUCTO_PROVEEDOR, ID_PRODUCTO, ID_PROVEEDOR, COSTO_COMPRA) VALUES (3, 2, 1, 30500); -- mismo Taladro, mas barato via proveedor 1
INSERT INTO PRODUCTOS_PROVEEDORES (ID_PRODUCTO_PROVEEDOR, ID_PRODUCTO, ID_PROVEEDOR, COSTO_COMPRA) VALUES (4, 3, 1, 4200);
INSERT INTO PRODUCTOS_PROVEEDORES (ID_PRODUCTO_PROVEEDOR, ID_PRODUCTO, ID_PROVEEDOR, COSTO_COMPRA) VALUES (5, 3, 3, 4450); -- mismo Cemento, mas caro via proveedor 3
INSERT INTO PRODUCTOS_PROVEEDORES (ID_PRODUCTO_PROVEEDOR, ID_PRODUCTO, ID_PROVEEDOR, COSTO_COMPRA) VALUES (6, 4, 1, 2800);
INSERT INTO PRODUCTOS_PROVEEDORES (ID_PRODUCTO_PROVEEDOR, ID_PRODUCTO, ID_PROVEEDOR, COSTO_COMPRA) VALUES (7, 5, 3, 9800);
INSERT INTO PRODUCTOS_PROVEEDORES (ID_PRODUCTO_PROVEEDOR, ID_PRODUCTO, ID_PROVEEDOR, COSTO_COMPRA) VALUES (8, 6, 3, 8200);
INSERT INTO PRODUCTOS_PROVEEDORES (ID_PRODUCTO_PROVEEDOR, ID_PRODUCTO, ID_PROVEEDOR, COSTO_COMPRA) VALUES (9, 7, 1, 2100);
INSERT INTO PRODUCTOS_PROVEEDORES (ID_PRODUCTO_PROVEEDOR, ID_PRODUCTO, ID_PROVEEDOR, COSTO_COMPRA) VALUES (10, 8, 1, 1600);

-- INVENTARIO: el Taladro (2) queda BAJO su minimo, a proposito (stock critico)
INSERT INTO INVENTARIO (ID_INVENTARIO, ID_PRODUCTO, CANTIDAD, CANTIDAD_MINIMA) VALUES (1, 1, 15, 5);
INSERT INTO INVENTARIO (ID_INVENTARIO, ID_PRODUCTO, CANTIDAD, CANTIDAD_MINIMA) VALUES (2, 2, 2, 5);  -- bajo el minimo
INSERT INTO INVENTARIO (ID_INVENTARIO, ID_PRODUCTO, CANTIDAD, CANTIDAD_MINIMA) VALUES (3, 3, 100, 20);
INSERT INTO INVENTARIO (ID_INVENTARIO, ID_PRODUCTO, CANTIDAD, CANTIDAD_MINIMA) VALUES (4, 4, 60, 10);
INSERT INTO INVENTARIO (ID_INVENTARIO, ID_PRODUCTO, CANTIDAD, CANTIDAD_MINIMA) VALUES (5, 5, 30, 5);
INSERT INTO INVENTARIO (ID_INVENTARIO, ID_PRODUCTO, CANTIDAD, CANTIDAD_MINIMA) VALUES (6, 6, 20, 5);
INSERT INTO INVENTARIO (ID_INVENTARIO, ID_PRODUCTO, CANTIDAD, CANTIDAD_MINIMA) VALUES (7, 7, 50, 10);
INSERT INTO INVENTARIO (ID_INVENTARIO, ID_PRODUCTO, CANTIDAD, CANTIDAD_MINIMA) VALUES (8, 8, 40, 10);

-- ----------------------------------------------------------------------------
-- CONDICIONES_PAGO Y METODOS_PAGO
-- ----------------------------------------------------------------------------
INSERT INTO CONDICIONES_PAGO (ID_CONDICION_PAGO, NOMBRE, DIAS_PLAZO) VALUES (1, 'Contado', 0);
INSERT INTO CONDICIONES_PAGO (ID_CONDICION_PAGO, NOMBRE, DIAS_PLAZO) VALUES (2, '30 dias', 30);
INSERT INTO CONDICIONES_PAGO (ID_CONDICION_PAGO, NOMBRE, DIAS_PLAZO) VALUES (3, '60 dias', 60);

INSERT INTO METODOS_PAGO (ID_METODO_PAGO, NOMBRE) VALUES (1, 'Efectivo');
INSERT INTO METODOS_PAGO (ID_METODO_PAGO, NOMBRE) VALUES (2, 'Debito');
INSERT INTO METODOS_PAGO (ID_METODO_PAGO, NOMBRE) VALUES (3, 'Credito');
INSERT INTO METODOS_PAGO (ID_METODO_PAGO, NOMBRE) VALUES (4, 'Transferencia');
INSERT INTO METODOS_PAGO (ID_METODO_PAGO, NOMBRE) VALUES (5, 'Cheque');

-- ----------------------------------------------------------------------------
-- 9-10. COMPRA_PROVEEDOR Y DETALLE_COMPRA_PROVEEDOR
-- ----------------------------------------------------------------------------
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (1, 1, 1, 2, TO_DATE('2025-06-05','YYYY-MM-DD'), 'COMPLETADO');
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (2, 3, 1, 1, TO_DATE('2025-06-12','YYYY-MM-DD'), 'COMPLETADO');
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (3, 1, 3, 2, TO_DATE('2025-07-01','YYYY-MM-DD'), 'COMPLETADO');
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (4, 2, 3, 1, TO_DATE('2025-07-03','YYYY-MM-DD'), 'COMPLETADO');
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (5, 3, 3, 1, TO_DATE('2025-07-04','YYYY-MM-DD'), 'COMPLETADO');
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (6, 1, 3, 2, TO_DATE('2025-07-06','YYYY-MM-DD'), 'COMPLETADO');
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (7, 1, 1, 1, TO_DATE('2025-07-08','YYYY-MM-DD'), 'PENDIENTE');
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (8, 2, 3, 3, TO_DATE('2025-07-09','YYYY-MM-DD'), 'COMPLETADO');
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (9, 3, 3, 1, TO_DATE('2025-07-10','YYYY-MM-DD'), 'COMPLETADO');
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (10, 1, 1, 1, TO_DATE('2025-07-11','YYYY-MM-DD'), 'COMPLETADO');
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (11, 2, 3, 2, TO_DATE('2025-07-13','YYYY-MM-DD'), 'PENDIENTE');
INSERT INTO COMPRA_PROVEEDOR (ID_COMPRA_STOCK, ID_PROVEEDOR, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_COMPRA, ESTADO)
VALUES (12, 1, 3, 1, TO_DATE('2025-07-14','YYYY-MM-DD'), 'COMPLETADO');


INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (1, 1, 3, 100, 4200);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (2, 1, 7, 50, 2100);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (3, 2, 5, 30, 9800);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (4, 2, 6, 20, 8200);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (5, 3, 1, 30, 5500);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (6, 3, 7, 100, 2100);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (7, 4, 2, 5, 32000);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (8, 5, 5, 40, 9800);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (9, 5, 6, 25, 8200);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (10, 6, 8, 60, 1600);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (11, 7, 2, 3, 30500);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (12, 8, 2, 4, 32000);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (13, 9, 3, 80, 4450);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (14, 10, 4, 50, 2800);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (15, 11, 1, 20, 5500);
INSERT INTO DETALLE_COMPRA_PROVEEDOR (ID_DETALLE_COMPRA, ID_COMPRA_STOCK, ID_PRODUCTO, CANTIDAD, COSTO_UNITARIO) 
VALUES (16, 12, 7, 80, 2100);

-- ----------------------------------------------------------------------------
-- MOVIMIENTOS_INVENTARIO
-- ----------------------------------------------------------------------------
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA)
VALUES (1, 3, 3, 'ENTRADA', 100, TO_DATE('2025-06-05','YYYY-MM-DD'), 'COMPRA-1');
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA)
VALUES (2, 7, 3, 'ENTRADA', 50, TO_DATE('2025-06-05','YYYY-MM-DD'), 'COMPRA-1');
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA)
VALUES (3, 5, 3, 'ENTRADA', 30, TO_DATE('2025-06-12','YYYY-MM-DD'), 'COMPRA-2');
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA)
VALUES (4, 6, 3, 'ENTRADA', 20, TO_DATE('2025-06-12','YYYY-MM-DD'), 'COMPRA-2');
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA)
VALUES (5, 1, 2, 'SALIDA', 2, TO_DATE('2025-06-20','YYYY-MM-DD'), 'VENTA-1');
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA)
VALUES (6, 2, 2, 'SALIDA', 6, TO_DATE('2025-06-28','YYYY-MM-DD'), 'VENTA-4');
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA) 
VALUES (7, 1, 3, 'ENTRADA', 30, TO_DATE('2025-07-01','YYYY-MM-DD'), 'COMPRA-3');
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA) 
VALUES (8, 7, 3, 'ENTRADA', 100, TO_DATE('2025-07-01','YYYY-MM-DD'), 'COMPRA-3');
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA) 
VALUES (9, 2, 3, 'ENTRADA', 5, TO_DATE('2025-07-03','YYYY-MM-DD'), 'COMPRA-4');
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA) 
VALUES (10, 2, 2, 'SALIDA', 1, TO_DATE('2025-07-01','YYYY-MM-DD'), 'VENTA-4');
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA) 
VALUES (11, 3, 3, 'ENTRADA', 80, TO_DATE('2025-07-10','YYYY-MM-DD'), 'COMPRA-9');
INSERT INTO MOVIMIENTOS_INVENTARIO (ID_MOVIMIENTO, ID_PRODUCTO, ID_EMPLEADO, TIPO_MOVIMIENTO, CANTIDAD, FECHA_MOVIMIENTO, REFERENCIA) 
VALUES (12, 8, 2, 'SALIDA', 10, TO_DATE('2025-07-02','YYYY-MM-DD'), 'VENTA-5');

-- ----------------------------------------------------------------------------
-- 13-14. VENTA_CLIENTE Y DETALLE_VENTAS
-- ----------------------------------------------------------------------------
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (1, 1, 2, 1, TO_DATE('2025-06-20','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (2, 3, 2, 1, TO_DATE('2025-06-24','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (3, 2, 2, 1, TO_DATE('2025-06-27','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (4, 1, 2, 1, TO_DATE('2025-07-01','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (5, 2, 2, 1, TO_DATE('2025-07-02','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (6, 3, 4, 1, TO_DATE('2025-07-03','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (7, 1, 2, 2, TO_DATE('2025-07-05','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (8, 2, 4, 1, TO_DATE('2025-07-07','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (9, 3, 2, 1, TO_DATE('2025-07-08','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (10, 1, 4, 1, TO_DATE('2025-07-10','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (11, 2, 2, 3, TO_DATE('2025-07-11','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (12, 3, 4, 1, TO_DATE('2025-07-12','YYYY-MM-DD'), 'EMITIDA');
INSERT INTO VENTA_CLIENTE (ID_COMPRA_CLIENTE, ID_CLIENTE, ID_EMPLEADO, ID_CONDICION_PAGO, FECHA_VENTA, ESTADO)
VALUES (13, 1, 2, 1, TO_DATE('2025-07-14','YYYY-MM-DD'), 'EMITIDA');

INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (1, 1, 1, 2, 8990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (2, 1, 3, 10, 6490, 5);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (3, 2, 7, 3, 3990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (4, 2, 4, 20, 4290, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (5, 3, 8, 5, 2990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (6, 3, 6, 1, 12990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (7, 4, 2, 1, 45990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (8, 5, 1, 3, 8990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (9, 5, 8, 10, 2990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (10, 6, 3, 25, 6490, 10);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (11, 7, 5, 2, 15990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (12, 8, 4, 15, 4290, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (13, 8, 7, 2, 3990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (14, 9, 6, 1, 12990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (15, 10, 1, 1, 8990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (16, 10, 3, 5, 6490, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (17, 11, 5, 3, 15990, 5);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (18, 12, 7, 4, 3990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (19, 13, 8, 20, 2990, 0);
INSERT INTO DETALLE_VENTAS (ID_DETALLE_VENTA, ID_COMPRA_CLIENTE, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO) 
VALUES (20, 13, 4, 10, 4290, 0);


-- ----------------------------------------------------------------------------
-- PAGOS
-- ----------------------------------------------------------------------------
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO)
VALUES (1, 1, 1, 79635, TO_DATE('2025-06-20','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO)
VALUES (2, 2, 3, 60000, TO_DATE('2025-06-24','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO)
VALUES (3, 2, 4, 37770, TO_DATE('2025-06-24','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO)
VALUES (4, 3, 5, 20000, TO_DATE('2025-06-27','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO) 
VALUES (5, 4, 2, 45990, TO_DATE('2025-07-01','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO) 
VALUES (6, 5, 1, 56870, TO_DATE('2025-07-02','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO) 
VALUES (7, 7, 4, 31980, TO_DATE('2025-07-05','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO) 
VALUES (8, 8, 2, 50000, TO_DATE('2025-07-07','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO) 
VALUES (9, 8, 1, 22330, TO_DATE('2025-07-07','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO) 
VALUES (10, 9, 5, 12990, TO_DATE('2025-07-08','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO) 
VALUES (11, 10, 1, 30000, TO_DATE('2025-07-10','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO) 
VALUES (12, 11, 3, 45572, TO_DATE('2025-07-11','YYYY-MM-DD'), 'APROBADO');
INSERT INTO PAGOS (ID_PAGO, ID_COMPRA_CLIENTE, ID_METODO_PAGO, MONTO, FECHA_PAGO, ESTADO) 
VALUES (13, 12, 2, 15960, TO_DATE('2025-07-12','YYYY-MM-DD'), 'APROBADO');

-- ----------------------------------------------------------------------------
-- DEVOLUCION Y DET_DEVOLUCION
-- Cliente 1 devuelve 1 de los 2 martillos comprados en la venta 1 (producto defectuoso).
-- ----------------------------------------------------------------------------
INSERT INTO DEVOLUCION (ID_DEVOLUCION, ID_COMPRA_CLIENTE, ID_EMPLEADO, MOTIVO, FECHA_DEVOLUCION, ESTADO, OBSERVACION)
VALUES (1, 1, 2, 'Producto defectuoso', TO_DATE('2025-06-22','YYYY-MM-DD'), 'APROBADA', 'Mango del martillo agrietado');

INSERT INTO DET_DEVOLUCION (ID_DETALLE_DEVOLUCION, ID_DEVOLUCION, ID_DETALLE_VENTA, CANTIDAD, MONTO_REEMBOLSO)
VALUES (1, 1, 1, 1, 8990);

COMMIT;

-- ============================================================================
-- VERIFICACIONES
-- ============================================================================

-- 1) Comparacion de costos entre proveedores para el mismo producto
SELECT p.nombre AS producto, pr.razon_social AS proveedor, pp.costo_compra
FROM productos_proveedores pp
JOIN productos p ON p.id_producto = pp.id_producto
JOIN proveedores pr ON pr.id_proveedor = pp.id_proveedor
WHERE pp.id_producto IN (2, 3)
ORDER BY p.id_producto, pp.costo_compra;

-- 2) Producto bajo su stock minimo
SELECT p.nombre, i.cantidad, i.cantidad_minima
FROM inventario i JOIN productos p ON p.id_producto = i.id_producto
WHERE i.cantidad < i.cantidad_minima;

-- 3) Saldo pendiente por venta (total detalle - pagos)
SELECT vc.id_compra_cliente,
       SUM(dv.cantidad * dv.precio_unitario * (1 - dv.descuento / 100)) AS total_venta,
       NVL((SELECT SUM(monto) FROM pagos WHERE id_compra_cliente = vc.id_compra_cliente), 0) AS total_pagado,
       SUM(dv.cantidad * dv.precio_unitario * (1 - dv.descuento / 100))
         - NVL((SELECT SUM(monto) FROM pagos WHERE id_compra_cliente = vc.id_compra_cliente), 0) AS saldo_pendiente
FROM venta_cliente vc
JOIN detalle_ventas dv ON dv.id_compra_cliente = vc.id_compra_cliente
GROUP BY vc.id_compra_cliente
ORDER BY vc.id_compra_cliente;

-- 4) Devolucion registrada
SELECT d.id_devolucion, vc.id_compra_cliente, d.motivo, dd.cantidad, dd.monto_reembolso
FROM devolucion d
JOIN det_devolucion dd ON dd.id_devolucion = d.id_devolucion
JOIN venta_cliente vc ON vc.id_compra_cliente = d.id_compra_cliente;
